services:                         
    db:                                                                                            
      image: pgvector/pgvector:pg16                                                                
      environment:                                                                                 
        POSTGRES_USER: postgres                                                                    
        POSTGRES_PASSWORD: postgres                                                                
        POSTGRES_DB: lecturemind
      ports:                                                                                       
        - "5432:5432"
      volumes:                                                                                     
        - pgdata:/var/lib/postgresql/data
    api:
      build: "."
      environment:
        DATABASE_URL: postgresql://postgres:postgres@db:5432/lecturemind
      ports:
        - "8000:8000"
      depends_on:
        - "db"  
      env_file:
        - ".env"                                                                                                 
volumes:        
    pgdata: